openapi: 3.0.1
info:
  title: Authentication Management
  version: 0.0.1
servers:
- url: http://localhost:8082
  description: Generated server url
paths:
  /placeOrder:
    post:
      tags:
      - book-my-gift-controller
      operationId: placeOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderRequest'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Order'
  /api/v1/auth/register:
    post:
      tags:
      - authentication-controller
      operationId: register
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AuthResponse'
  /api/v1/auth/authenticate:
    post:
      tags:
      - authentication-controller
      operationId: authenticate
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AuthResponse'
  /showMyOrders:
    get:
      tags:
      - book-my-gift-controller
      operationId: showMyOrders
      parameters:
      - name: giftType
        in: query
        required: false
        schema:
          type: string
          enum:
          - KEYCHAIN
          - FRAME
      - name: orderStatus
        in: query
        required: false
        schema:
          type: string
          enum:
          - ORDER_RECIEVED
          - ITEM_DISPATCHED
          - ITEM_OUT_FOR_DELIVERY
          - CANCELLED
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
  /cancelOrder:
    delete:
      tags:
      - book-my-gift-controller
      operationId: cancelOrder
      parameters:
      - name: orderId
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Order'
components:
  schemas:
    OrderRequest:
      required:
      - amountPaid
      - giftType
      type: object
      properties:
        giftType:
          type: string
          enum:
          - KEYCHAIN
          - FRAME
        amountPaid:
          minimum: 300
          type: number
          format: double
    Order:
      type: object
      properties:
        orderId:
          type: string
        username:
          type: string
        emailId:
          type: string
        giftType:
          type: string
          enum:
          - KEYCHAIN
          - FRAME
        amountPaid:
          type: number
          format: double
        orderStatus:
          type: string
          enum:
          - ORDER_RECIEVED
          - ITEM_DISPATCHED
          - ITEM_OUT_FOR_DELIVERY
          - CANCELLED
    AuthRequest:
      required:
      - email
      - fullname
      - password
      - username
      type: object
      properties:
        username:
          maxLength: 20
          minLength: 3
          type: string
        password:
          maxLength: 20
          minLength: 8
          type: string
        email:
          type: string
        fullname:
          maxLength: 20
          minLength: 3
          type: string
    AuthResponse:
      type: object
      properties:
        token:
          type: string
