version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: myuser
    ports:
      - 5432:5432
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  sonarqube:
    image: sonarqube:latest
    ports:
      - 9000:9000