version: '3'
services:
  web:
    image: joseph24x7/bookmygift:latest
    container_name: web
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/myuser
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=mypassword
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=admin
      - SPRING_RABBITMQ_PASSWORD=password
      - SPRING_RABBITMQ_HOST=rabbitmq
    networks:
      - mynetwork

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: myuser
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - mynetwork

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_ERLANG_COOKIE='secretpass'
      - RABBITMQ_USE_LONGNAME=true
    networks:
      - mynetwork

  postfix:
    image: postfixadmin:latest
    environment:
      POSTFIX_SMTP_HOST: $$\{mail.host:}
      POSTFIX_SMTP_PORT: $$\{mail.port:}
      POSTFIX_SMTP_USERNAME: $$\{mail.username:}
      POSTFIX_SMTP_PASSWORD: $$\{mail.password:}
      POSTFIX_SMTP_AUTH: $$\{mail.properties.mail.smtp.auth:}
      POSTFIX_SMTP_STARTTLS_ENABLE: $$\{mail.properties.mail.smtp.starttls.enable:}
    networks:
      - mynetwork

  configserver:
    container_name: configserver
    image: joseph24x7/configserver:latest
    ports:
      - 8888:8888
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/myuser
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge