version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: myuser
    ports:
      - 5432:5432
    volumes:
      - /my/data/directory:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  sonarqube:
    image: sonarqube:latest
    ports:
      - 9000:9000
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_ERLANG_COOKIE='secretpass'
      - RABBITMQ_USE_LONGNAME=true
  postfix:
    image: postfixadmin:latest
    environment:
      POSTFIX_SMTP_HOST: smtp.gmail.com
      POSTFIX_SMTP_PORT: 587
      POSTFIX_SMTP_USERNAME: rabbitmqdocker@gmail.com
      POSTFIX_SMTP_PASSWORD: sosiqoxkyqtktxhs
      POSTFIX_SMTP_AUTH: true
      POSTFIX_SMTP_STARTTLS_ENABLE: true