server:
   port: 8082

spring:
   datasource:
      url: jdbc:postgresql://localhost:5432/myuser
      username: myuser
      password: mypassword
   jpa:
      hibernate:
         ddl-auto: update
      show-sql: true
      properties:
         hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
   data:
      mongodb:
         uri: mongodb+srv://Joseph24x7:Abcde12345@joseph24x7.0vl2a0k.mongodb.net/?retryWrites=true&w=majority
         database: BookMyGift
   redis:
      host: redis
      port: 6379
   rabbitmq:
      host: localhost
      port: 5672
      username: admin
      password: password
   mail:
      host: smtp.gmail.com
      port: 587
      username: gmail.com
      password: password
      properties.mail.smtp.auth: true
      properties.mail.smtp.starttls.enable: true
         
management:
   endpoints:
      web:
         exposure:
            include: "*"
            exclude: beans
   health:
      show-details: always
      
logging:
   pattern:
      file: '%d{yyyy-MM-dd HH:mm:ss,SSS} %5p [%t] %c [%M] - %m%n'
   level:
      com.bookmygift: DEBUG
      org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG