name: Docker Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Build with Maven
        run: mvn clean install -Dmaven.version=3.9.3
      - name: Log in to Docker Hub
        run: docker login -u joseph24x7 -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image
        run: docker build -t joseph24x7/bookmyticket .
      - name: Push image to Docker Hub
        run: docker push joseph24x7/bookmyticket
