name: Maven Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK and Maven
        run: |
          wget -q https://download.java.net/java/GA/jdk17.0.1/2b70219e874a4f5aaa6bebe55d254c55/12/GPL/openjdk-17.0.1_linux-x64_bin.tar.gz
          tar xzf openjdk-17.0.1_linux-x64_bin.tar.gz
          export JAVA_HOME=$RUNNER_WORKSPACE/jdk-17.0.1
          export PATH=$JAVA_HOME/bin:$PATH

          wget -q https://archive.apache.org/dist/maven/maven-3/3.9.3/binaries/apache-maven-3.9.3-bin.tar.gz
          tar xzf apache-maven-3.9.3-bin.tar.gz
          export MAVEN_HOME=$RUNNER_WORKSPACE/apache-maven-3.9.3
          export PATH=$MAVEN_HOME/bin:$PATH

      - name: Build with Maven
        run: mvn clean install
